spring:
  application:
    name: billing

  config:
    import:
      - "aws-secretsmanager:billing/dev/db-credentials?prefix=db.;billing/dev/jwt-secret"
      - "aws-parameterstore:/billing/dev/"

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${db.username}
    password: ${db.password}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        profile:
          name: billing-dev
      sqs:
        queue-not-found-strategy: fail

jwt:
  secret: ${jwt-secret}
  expiration-ms: 3600000